// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBz6igMncRe-2-HJ75wvc5DZISPcyWXus',
    appId: '1:1015366964970:web:1559948a9af273d9c92993',
    messagingSenderId: '1015366964970',
    projectId: 'yack-aeb34',
    authDomain: 'yack-aeb34.firebaseapp.com',
    storageBucket: 'yack-aeb34.firebasestorage.app',
    measurementId: 'G-V5X6456XHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASxMoPm7ATUE93PHNwZIN4mGwE7E8iQxk',
    appId: '1:1015366964970:android:b1e428749aed4d87c92993',
    messagingSenderId: '1015366964970',
    projectId: 'yack-aeb34',
    storageBucket: 'yack-aeb34.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBz6igMncRe-2-HJ75wvc5DZISPcyWXus',
    appId: '1:1015366964970:web:15d67d420d410e12c92993',
    messagingSenderId: '1015366964970',
    projectId: 'yack-aeb34',
    authDomain: 'yack-aeb34.firebaseapp.com',
    storageBucket: 'yack-aeb34.firebasestorage.app',
    measurementId: 'G-79MWHENCLZ',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gfuiMix4du0sF7YIuh0Velx9cecAZCA',
    appId: '1:1015366964970:ios:8e950aacf1e99c50c92993',
    messagingSenderId: '1015366964970',
    projectId: 'yack-aeb34',
    storageBucket: 'yack-aeb34.firebasestorage.app',
    iosBundleId: 'com.example.yack',
  );
}
